{{- if .Values.apiServer.generated_certs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres-operator.fullname" . }}-apiserver
  labels:
    app: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "files/apiserver/*").AsSecrets | indent 2 }}
{{- end }}