{{- if .Values.pgcluster_creation }}
{{- range .Values.pgcluster }}
apiVersion: v1
stringData:
  password: {{ .secret.postgres.password }}
  username: postgres
kind: Secret
metadata:
  labels:
    pg-database: {{ .name }}
  name: {{ .name }}-postgres-secret
  namespace: {{ .namespace }}
type: Opaque
---
apiVersion: v1
stringData:
  password: {{ .secret.primaryuser.password }}
  username: primaryuser
kind: Secret
metadata:
  labels:
    pg-database: {{ .name }}
  name: {{ .name }}-primaryuser-secret
  namespace: {{ .namespace }}
type: Opaque
---
apiVersion: v1
stringData:
  password: {{ .secret.testuser.password }}
  username: testuser
kind: Secret
metadata:
  labels:
    pg-database: {{ .name }}
  name: {{ .name }}-testuser-secret
  namespace: {{ .namespace }}
type: Opaque
---
{{- end}}
{{- end}}