apiVersion: ENC[AES256_GCM,data:qpU=,iv:Ruakx30IroDz+AvJpUHaKG/mEOg4ESKjbvS5BzxpqPc=,tag:BKTzx7Gi4RSG5PwgtOCB5w==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FwvSP81cAV1vlbDl51LsTa56Pw8JCuQ1UplDBBYdS+6jeDYTIpCjOMB1YUGaeZK0riCEW1E1jQyyLccbPGL7HwEn+/kunv7OGsLQYd2eQIPPIpvRDVi83q+i0bbdiwqwIBinkbIwuW9XoHQXK0YlMFjMNw6KgooA5l4O+gJJTVtLjbFFWGQmcWO3rsAPw2PspVYB9fi2E/6Q4SljQEfGuj/RhY+veG/mHqloJ9SCkNeh+iv+enErX3cjVYLneAnzH2CyiapkPiIUXD/cGQXdc3HTI1Qe8qah34aSmA==,iv:JQpW1EK013s9sHO/6hGBw4VGOOYGeM9Kz9WAdpRpGkI=,tag:OICAwGDeHS5bIV3bvh9+IQ==,type:str]
kind: ENC[AES256_GCM,data:agOc3HBp,iv:iNy12vRY1XtPzJH8+8sMAkhqfUv/GTBMbn05EKw1UH0=,tag:TOQeKbhFREzhSKY7OVlENg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tRRiPDUdUgoU6Ed8S0WM/02J,iv:cCJ8L2dvZA45k2CGbMkZCmF971hqeTVTez2hMZ77Lo4=,tag:ys5jrsI8IJCrZ+5GrGfJkw==,type:str]
type: ENC[AES256_GCM,data:nPqSNgxdkg6xfjk9efQSyb47wasTbXZs54Uogeb0,iv:/d1iMNhocLoL5wenBGlG3Y4IkygQURiC6x/2KnAnHN0=,tag:73AP83LgJ+XaPyzrXIVblw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://estore-sops.vault.azure.net
        name: sops-key
        version: 539bc57229a24ff88895dcdf5ef84127
        created_at: '2019-06-04T23:20:41Z'
        enc: g2vbLDUBRWLwV2ZjMiIwD-JsWa6m7akz2ZIGYR0ynJw20ff5SrW-GZrtmP6VsRd4M7aCi87ACtlsCBJDy9pJ11AnQdCxaLLpHrc3ePMM9ae8KTrcKq8C8ceXCSpGks9L2kIAoCh-Nr-7FQ8JfpixE0lP6PQOoW6duR1Q0EqCCySO_2a4JUJettDK4oovSmAVB3XesoeK_nUNhWxeRUILi7YiuM0zGOsZX9Xu7MY0CaH3pyQKjpE6SetjgnDyIPdrI-ADzOeyp7CBDfxw4NtYAmxyVR8cu0ZnFMxkgx1TM9ucYsrcXqcj3FYvtewfvc7ZTfuAeuD_Hf9NzojdXGgBiQ
    lastmodified: '2019-06-04T23:20:41Z'
    mac: ENC[AES256_GCM,data:2WhuF9UQkokollFoz0C8dMW5baS3lwwZ3/vVGIXDrFA0hso29stDBujLlHx429znWcr+fE2wtCFm+3PVZKaNOHFkNK5h5cfk2htzP9jwK0Vn8aV+JaTURU1IoPkGYJdVb/gNi1TjO5em852kQ8E1haiIhX5KLlFPPb7CeTI21Uk=,iv:/jXp2Y55uLj23O/FYuT5Hfskippv+JLjAJyZZp1Bi9U=,tag:Wa6Q4DownvmzcR0QpoXaLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.2.0
